// ArcRotateCamera collision support is registered through this Babylon side effect.
// Keep it explicit: the tree-shaken facade otherwise builds but fails on its first frame.
import '@babylonjs/core/Collisions/collisionCoordinator'

export { Node } from '@babylonjs/core/node'
export { AbstractMesh } from '@babylonjs/core/Meshes/abstractMesh'
export { Mesh } from '@babylonjs/core/Meshes/mesh'
export { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder'
export { TransformNode } from '@babylonjs/core/Meshes/transformNode'
export { Vector3 } from '@babylonjs/core/Maths/math.vector'
export { Color3, Color4 } from '@babylonjs/core/Maths/math.color'
export { Engine } from '@babylonjs/core/Engines/engine'
export { EngineStore } from '@babylonjs/core/Engines/engineStore'
export { Scene } from '@babylonjs/core/scene'
export { SceneLoader } from '@babylonjs/core/Loading/sceneLoader'
export { AnimationGroup } from '@babylonjs/core/Animations/animationGroup'
export { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera'
export { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight'
export { DirectionalLight } from '@babylonjs/core/Lights/directionalLight'
export { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator'
export { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial'
export { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture'
export { Texture } from '@babylonjs/core/Materials/Textures/texture'
